//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class AdminManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected global::System.Web.UI.WebControls.TextBox txtAdminName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminName;
        protected global::System.Web.UI.WebControls.TextBox txtAdminEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revAdminEmail;
        protected global::System.Web.UI.WebControls.TextBox txtAdminContact;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminContact;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revAdminContact;
        protected global::System.Web.UI.WebControls.DropDownList ddlAdminCity;
        protected global::System.Web.UI.WebControls.DropDownList ddlAdminRole;
        protected global::System.Web.UI.WebControls.TextBox txtAdminPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminPassword;
        protected global::System.Web.UI.WebControls.TextBox txtAdminConfirm;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminConfirm;
        protected global::System.Web.UI.WebControls.CompareValidator cvAdminConfirm;
        protected global::System.Web.UI.WebControls.Button btnCreateAdmin;
        protected global::System.Web.UI.WebControls.Literal litUserCount;
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
