//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class AdminOrders
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseAlert;

        protected global::System.Web.UI.WebControls.Literal litTotalOrders;
        protected global::System.Web.UI.WebControls.Literal litPendingOrders;
        protected global::System.Web.UI.WebControls.Literal litProcessingOrders;
        protected global::System.Web.UI.WebControls.Literal litDeliveredOrders;

        protected global::System.Web.UI.WebControls.Panel pnlOrderItemsDetail;
        protected global::System.Web.UI.WebControls.Literal litSelectedOrderNum;
        protected global::System.Web.UI.WebControls.Button btnCloseItems;
        protected global::System.Web.UI.WebControls.GridView gvOrderItems;

        protected global::System.Web.UI.WebControls.Button btnFilterAll;
        protected global::System.Web.UI.WebControls.Button btnFilterPending;
        protected global::System.Web.UI.WebControls.Button btnFilterProcessing;
        protected global::System.Web.UI.WebControls.Button btnFilterDelivered;
        protected global::System.Web.UI.WebControls.Button btnFilterCancelled;

        protected global::System.Web.UI.WebControls.Repeater rptOrders;
        protected global::System.Web.UI.WebControls.Panel pnlNoOrders;
    }
}
