//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class AdminDashboard
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.Literal litTotalUsers;
        protected global::System.Web.UI.WebControls.Literal litTotalProducts;
        protected global::System.Web.UI.WebControls.Literal litTotalOrders;
        protected global::System.Web.UI.WebControls.Literal litTotalDiseases;
        protected global::System.Web.UI.WebControls.GridView gvRecentOrders;
        protected global::System.Web.UI.WebControls.GridView gvRecentUsers;
    }
}
