//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class Features
    {
        protected global::System.Web.UI.WebControls.Button Explore_btn;
        protected global::System.Web.UI.WebControls.Image FeatureImage;
        protected global::System.Web.UI.WebControls.Button btnGetStartedFree;
    }
}
