//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class Products
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCatAll;
        protected global::System.Web.UI.WebControls.LinkButton btnCatPlants;
        protected global::System.Web.UI.WebControls.LinkButton btnCatSeeds;
        protected global::System.Web.UI.WebControls.LinkButton btnCatFertilizers;
        protected global::System.Web.UI.WebControls.LinkButton btnCatPots;
        protected global::System.Web.UI.WebControls.LinkButton btnCatTools;
        protected global::System.Web.UI.WebControls.LinkButton btnCatCare;
        protected global::System.Web.UI.WebControls.LinkButton btnCatGifts;
        protected global::System.Web.UI.WebControls.Repeater rptProducts;
    }
}
