//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    public partial class Reports
    {
        protected global::System.Web.UI.WebControls.Literal litRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalOrders;
        protected global::System.Web.UI.WebControls.Literal litPlacedOrders;
        protected global::System.Web.UI.WebControls.Literal litDeliveredOrders;
        protected global::System.Web.UI.WebControls.GridView gvOrdersReport;
        protected global::System.Web.UI.WebControls.GridView gvInventoryReport;
    }
}
